import { useParams } from 'react-router-dom'
import DataConfidence from '../components/data/DataConfidence.jsx'
import Button from '../components/ui/Button.jsx'
import SeverityBadge from '../components/ui/SeverityBadge.jsx'
import { toast } from '../components/ui/toast.js'
import { DEMO_EVENT, REPORT, RISK } from '../utils/mockData.js'

export default function Report() {
  const { eventId } = useParams()
  const e = DEMO_EVENT

  return (
    <div className="mx-auto max-w-3xl">
      <header className="mb-5 flex flex-wrap items-start justify-between gap-3">
        <div>
          <div className="flex flex-wrap items-center gap-2">
            <h1 className="text-xl font-bold text-text">AI Emergency Situation Report</h1>
            <span className="rounded border border-medium/50 bg-medium/10 px-1.5 py-0.5 font-mono text-[9px] font-semibold uppercase tracking-wider text-medium">
              Demo data
            </span>
            <span className="rounded border border-border bg-panel2 px-1.5 py-0.5 font-mono text-[9px] font-semibold uppercase tracking-wider text-muted">
              source: {REPORT.source}
            </span>
          </div>
          <p className="mt-1 font-mono text-xs text-muted">
            {e.name} · event {eventId} · generated {e.updatedAt}
          </p>
        </div>
        <div className="flex gap-2">
          <Button
            size="sm"
            variant="secondary"
            onClick={() => toast.success('Report regenerated from evidence (mock)')}
          >
            Regenerate with AI
          </Button>
          <Button size="sm" onClick={() => window.print()}>Download PDF</Button>
        </div>
      </header>

      {/* meta summary */}
      <div className="mb-6 grid grid-cols-2 gap-3 rounded-lg border border-border bg-panel p-4 sm:grid-cols-4">
        <Meta label="Severity" value={<SeverityBadge band={e.severity.band} size="sm" />} />
        <Meta label="Risk score" value={<span className="font-mono">{RISK.score} / 100</span>} />
        <Meta label="Affected area" value={<span className="font-mono">{e.affectedAreaKm2} km²</span>} />
        <Meta label="Confidence" value={<span className="font-mono">{e.detection.confidence}</span>} />
      </div>

      {/* sections */}
      <article className="space-y-6">
        {REPORT.sections.map((s) => (
          <section key={s.id} className="rounded-lg border border-border bg-panel p-5">
            <div className="mb-2 flex flex-wrap items-center justify-between gap-2">
              <h2 className="text-sm font-semibold text-text">{s.title}</h2>
              <DataConfidence tags={s.provenance} />
            </div>

            {s.ordered ? (
              <ol className="space-y-2 text-sm leading-relaxed text-muted">
                {s.body.map((item, i) => (
                  <li key={i} className="flex gap-3">
                    <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-accent/15 font-mono text-[10px] font-semibold text-accent">
                      {i + 1}
                    </span>
                    <span>{item}</span>
                  </li>
                ))}
              </ol>
            ) : (
              <p className="text-sm leading-relaxed text-muted">{s.body}</p>
            )}
          </section>
        ))}
      </article>

      {/* disclaimer */}
      <div className="mt-6 rounded-lg border border-high/40 bg-high/10 p-4">
        <p className="text-[11px] font-semibold uppercase tracking-wider text-high">Disclaimer</p>
        <p className="mt-1 text-xs leading-relaxed text-muted">{REPORT.disclaimer}</p>
      </div>

      <div className="mt-4 flex flex-wrap items-center justify-between gap-3 text-[11px] text-muted">
        <span>
          {REPORT.source === 'template'
            ? 'Generated from the deterministic template (no LLM key configured).'
            : `Generated by ${REPORT.model}.`}
        </span>
        <span>schema v1.0 · evidence validated before generation</span>
      </div>
    </div>
  )
}

function Meta({ label, value }) {
  return (
    <div>
      <p className="text-[10px] uppercase tracking-wider text-muted">{label}</p>
      <div className="mt-1 text-sm text-text">{value}</div>
    </div>
  )
}
